export function downloadScore() {
    const content = this.codeEditor.getValue();
    const blob = new Blob([content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "score.scofo";
    a.click();
}

export function getPitch(note) {
    let pitch = `${note.step}`;
    if (note.alter) {
        if (note.alter == "1") {
            pitch += `#`;
        } else if (note.alter == "-1") {
            pitch += "b";
        } else {
            alert("accident " + note.alter + "is not supported by OpenScofo yet");
        }
    }
    pitch += `${note.octave}`;
    return pitch;
}

// ─────────────────────────────────────
export function generateOpenScofoScore() {
    let score = "";
    score += `/* Generated by OpenScofo online editor`;
    if (this.musicxmlScore.pieceName && this.musicxmlScore.pieceComposer) {
        score += `\n${this.musicxmlScore.pieceName} by ${this.musicxmlScore.pieceComposer}\n`;
        score += `*/\n\n`;
    } else {
        score += ` */\n\n`;
    }

    const measures = this.musicxmlScore.measures;
    const allNotes = [];
    for (const measureNumber in measures) {
        const measure = measures[measureNumber];
        for (const note of measure) {
            allNotes.push(note);
        }
    }

    let bpm = allNotes.length > 0 ? allNotes[0].bpm : 60;
    score += `BPM ${bpm}\n\n`;
    let i = 0;
    let lastMeasureNumber = null;

    if (this.musicxmlScore.useAIModel) {
        score += `// Your seems to be using extended techniques, this required one AI model\n`;
        score += `ONNXMODEL PUT-YOUR-MODEL-NAME-HERE.onnx\n`;
        score += `ONNXDESCRIPTORS mfcc logmel centroid flatness hfr flux zcr irregularity kurtosis`;
    }

    while (i < allNotes.length) {
        const note = allNotes[i];
        if (!note) {
            i++;
            continue;
        }

        // measure boundary
        if (note.measureNumber !== lastMeasureNumber) {
            score += `\n\n// Measure number ${note.measureNumber}`;
            lastMeasureNumber = note.measureNumber;
        }

        // BPM change
        if (note.bpm !== bpm) {
            bpm = note.bpm;
            score += `\nBPM ${bpm}\n`;
        }

        // REST
        if (note.isRest) {
            score += `\nREST ${note.duration}`;
            i++;
            continue;
        }

        // INITIAL STATE
        let duration = note.duration;
        let pitches = [this.getPitch(note)];
        let type = "NOTE";

        let j = i + 1;

        // TIES (safe chain)
        if (note.isTied) {
            while (j < allNotes.length && allNotes[j]?.isTied) {
                const n = allNotes[j];
                duration += n.duration;
                j++;
            }
        }

        // CHORD GROUPING (safe)
        if (note.isChord) {
            type = "CHORD";
            while (j < allNotes.length && allNotes[j]?.isChord) {
                pitches.push(this.getPitch(allNotes[j]));
                j++;
            }
        }

        // TREMOLO GROUPING (safe)
        if (note.isTremolo) {
            type = "TRILL";

            while (j < allNotes.length && allNotes[j]?.isTremolo) {
                pitches.push(this.getPitch(allNotes[j]));
                duration += allNotes[j].duration;

                if (allNotes[j].tremoloType === "stop") {
                    j++;
                    break;
                }

                j++;
            }
        }

        // EXTENDED TECHNIQUE
        if (note.isExtendedTechnique) {
            const pitch = this.getPitch(note);
            score += `\nPTECH ${note.notehead} ${pitch} ${duration}`;
            i = j;
            continue;
        }

        // OUTPUT
        if (pitches.length > 1) {
            score += `\n${type} (${pitches.join(" ")}) ${duration}`;
        } else {
            score += `\n${type} ${pitches[0]} ${duration}`;
        }

        if (note.isTied) {
            score += " // tied";
        }

        i = j;
    }

    this.codeEditor.setValue(score);
}

// ─────────────────────────────────────
export function parseScore(doc) {
    const part = doc.getElementsByTagName("score-partwise")[0];
    const measures = part.getElementsByTagName("measure");

    let bpm = 60;
    let beatUnit = "quarter";
    let metronomeMarkIsDotted = false;
    let beatsPerMeasure = 4;
    let timeSignatureDenominator = 4;

    this.musicxmlScore = {
        measures: {},
        useAIModel: false,
    };

    let divisionsFactor = 1;
    let isTremolo = false;
    let tremoloType = null;
    let isTied = false;
    let tiedType = null;

    // Credits (title/composer)
    const credits = part.getElementsByTagName("credit");
    for (let credit of credits) {
        const creditType = credit.getElementsByTagName("credit-type")[0];
        if (!creditType) continue;
        const text = creditType.textContent;
        const creditWords = credit.getElementsByTagName("credit-words");
        if (text === "title" && creditWords.length > 0) {
            this.musicxmlScore.pieceName = creditWords[0].textContent;
        }
        if (text === "composer" && creditWords.length > 0) {
            this.musicxmlScore.pieceComposer = creditWords[0].textContent;
        }
    }

    var measureNumber = 0;
    for (let measure of measures) {
        measureNumber++;
        const attributes = measure.getElementsByTagName("attributes")[0];
        if (attributes) {
            const divisions = attributes.getElementsByTagName("divisions")[0];
            if (divisions) {
                divisionsFactor = parseInt(divisions.textContent, 10);
            }
            const time = attributes.getElementsByTagName("time")[0];
            if (time) {
                const beats = time.getElementsByTagName("beats")[0];
                const beatType = time.getElementsByTagName("beat-type")[0];

                if (beats) beatsPerMeasure = parseInt(beats.textContent, 10);
                if (beatType) timeSignatureDenominator = parseInt(beatType.textContent, 10);
            }
        }

        const metronome = measure.getElementsByTagName("metronome")[0];
        if (metronome) {
            const beatUnitEl = metronome.getElementsByTagName("beat-unit")[0];
            const bpmEl = metronome.getElementsByTagName("per-minute")[0];
            const dot = metronome.getElementsByTagName("beat-unit-dot").length > 0;
            if (beatUnitEl) beatUnit = beatUnitEl.textContent;
            if (bpmEl) bpm = parseFloat(bpmEl.textContent);
            metronomeMarkIsDotted = dot;
        }

        const notes = measure.getElementsByTagName("note");
        const measureNotes = [];

        for (let i = 0; i < notes.length; i++) {
            const note = notes[i];
            const chord = note.getElementsByTagName("chord").length > 0;
            const pitch = note.getElementsByTagName("pitch")[0];
            const tremolo = note.getElementsByTagName("tremolo");
            const tied = note.getElementsByTagName("tied");
            const notehead = note.getElementsByTagName("notehead");

            // tremolo state
            if (tremolo.length > 0) {
                isTremolo = true;
                tremoloType = tremolo[0].getAttribute("type");
            } else {
                isTremolo = false;
                tremoloType = null;
            }

            // tied state
            if (tied.length > 0) {
                isTied = true;
                tiedType = tied[0].getAttribute("type");
            } else {
                isTied = false;
                tiedType = null;
            }
            // pitch extraction
            let step = null;
            let octave = null;
            let alter = null;

            if (pitch) {
                const stepEl = pitch.getElementsByTagName("step")[0];
                const octaveEl = pitch.getElementsByTagName("octave")[0];
                const alterEl = pitch.getElementsByTagName("alter")[0];
                if (stepEl) step = stepEl.textContent;
                if (octaveEl) octave = parseInt(octaveEl.textContent, 10);
                if (alterEl) alter = parseInt(alterEl.textContent, 10);
            }

            const durationEl = note.getElementsByTagName("duration")[0];
            const rawDuration = durationEl ? parseFloat(durationEl.textContent) : 0;
            const duration = rawDuration / (timeSignatureDenominator / divisionsFactor);
            const rest = note.getElementsByTagName("rest")[0];
            const noteheadString = notehead.length > 0 ? notehead[0].textContent : "";
            const isExtendedTechnique = notehead.length > 0;

            if (notehead.length > 0) {
                this.musicxmlScore.useAIModel = true;
            }

            let beatValueMultiplier = 1;

            if (beatUnit === "whole") beatValueMultiplier = 1;
            if (beatUnit === "half") beatValueMultiplier = 2;
            if (beatUnit === "quarter") beatValueMultiplier = 4;
            if (beatUnit === "eighth") beatValueMultiplier = 8;
            if (beatUnit === "16th") beatValueMultiplier = 16;
            if (beatUnit === "32nd") beatValueMultiplier = 32;

            if (metronomeMarkIsDotted) {
                beatValueMultiplier /= 1.5;
            }

            // console.log(timeSignatureDenominator, beatValueMultiplier);
            const normalizedBpm = bpm * (timeSignatureDenominator / beatValueMultiplier);

            const noteObj = {
                bpm: normalizedBpm,
                timeUnit: beatUnit,
                metronomeMarkDotted: metronomeMarkIsDotted,
                beatsPerMeasure,
                timeSignatureDenominator,
                step,
                octave,
                alter,
                duration,
                isRest: !!rest,
                isTremolo,
                tremoloType,
                isTied,
                tiedType,
                measureNumber,
                isChord: chord,
                isExtendedTechnique,
                notehead: noteheadString,
            };

            measureNotes.push(noteObj);
        }
        this.musicxmlScore.measures[measureNumber] = measureNotes;
    }

    this.generateOpenScofoScore();
    this.handleCodeChange();
}

// ─────────────────────────────────────
export function uploadWav() {
    const fileInput = document.getElementById("audioInput");
    if (!fileInput) {
        console.error("File input not found");
        return;
    }
    fileInput.click();
    fileInput.onchange = (event) => {
        const file = event.target.files[0];
        if (!file) {
            console.error("No file selected");
            return;
        }
        k;
    };
}

export function uploadScore() {
    const fileInput = document.getElementById("scoreXmlInput");
    if (!fileInput) {
        console.error("File input not found");
        return;
    }
    fileInput.click();
    fileInput.onchange = (event) => {
        const file = event.target.files[0];
        if (!file) {
            console.error("No file selected");
            return;
        }

        if (file.name.endsWith(".mxl")) {
            const reader = new FileReader();
            reader.onload = (e) => {
                JSZip.loadAsync(e.target.result)
                    .then((zip) => {
                        const xmlFile = Object.keys(zip.files).find(
                            (fileName) => fileName.endsWith(".xml") && !fileName.includes("META-INF/"),
                        );
                        if (xmlFile) {
                            zip.file(xmlFile)
                                .async("string")
                                .then((xmlString) => {
                                    const parser = new DOMParser();
                                    const doc = parser.parseFromString(xmlString, "application/xml");
                                    this.parseScore(doc);
                                })
                                .catch((error) => {
                                    alert("Error parsing XML:", error);
                                });
                        } else {
                            alert("No XML file found in the ZIP archive.");
                        }
                    })
                    .catch((error) => {
                        alert("Error extracting MXL file:", error);
                    });
            };
            reader.onerror = (error) => {
                alert("There was an error reading the file:", error);
            };
            reader.readAsArrayBuffer(file);
        } else if (file.name.endsWith(".xml") || file.name.endsWith(".musicxml")) {
            const reader = new FileReader();
            reader.onload = (e) => {
                const xmlString = e.target.result;
                const parser = new DOMParser();
                const doc = parser.parseFromString(xmlString, "application/xml");
                this.parseScore(doc);
            };
            reader.onerror = (error) => {
                alert("There was an error reading the file:", error);
            };
            reader.readAsText(file);
        } else {
            alert("Unsupported file type");
        }
    };
}

export function loadTxtScore() {
    const fileInput = document.getElementById("scoreTxtInput");
    if (!fileInput) {
        console.error("File input not found");
        return;
    }

    fileInput.click();
    fileInput.onchange = (event) => {
        const file = event.target.files[0];
        if (!file) {
            console.error("No file selected");
            return;
        }
        const reader = new FileReader();
        reader.onload = (e) => {
            const fileContent = e.target.result;
            this.codeEditor.setValue(fileContent);

            this.handleCodeChange();
        };
        reader.onerror = (e) => {
            console.error("Error reading file:", e);
        };
        reader.readAsText(file);
    };
}
