export function downloadScore() {
    const content = this.codeEditor.getValue();
    const blob = new Blob([content], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "score.scofo.txt";
    a.click();
}

export function getPitch(note) {
    let pitch = `${note.step}`;
    if (note.alter) {
        if (note.alter == "1") {
            pitch += `#`;
        } else if (note.alter == "-1") {
            pitch += "b";
        } else {
            alert("accident " + note.alter + "is not supported by OpenScofo yet");
        }
    }
    pitch += `${note.octave}`;
    return pitch;
}

export function generateOpenScofoScore() {
    let score = "";

    score += `/* Generated by OpenScofo online editor`;
    if (this.musicxmlScore.pieceName && this.musicxmlScore.pieceComposer) {
        score += `\n${this.musicxmlScore.pieceName} by ${this.musicxmlScore.pieceComposer}\n`;
        score += `*/\n\n`;
    } else {
        score += ` */\n\n`;
    }

    score += `BPM ${this.musicxmlScore.measures[1][0].bpm}`;
    let bpm = this.musicxmlScore.measures[1][0].bpm;
    let allNotes = [];

    for (let measureNumber in this.musicxmlScore.measures) {
        const measure = this.musicxmlScore.measures[measureNumber];
        for (let note of measure) {
            allNotes.push(note);
        }
    }

    let lastMeasureNumber = 0;
    for (let i = 0; i < allNotes.length; i++) {
        let note = allNotes[i];
        if (note !== undefined) {
            if (note.measureNumber != lastMeasureNumber) {
                score += `\n\n// Measure number ${note.measureNumber}`;
                lastMeasureNumber = note.measureNumber;
            }
        }
        if (note.bpm != bpm) {
            score += `\nBPM ${note.bpm}\n`;
            bpm = note.bpm;
        }
        score += "\n";
        if (note.isRest) {
            score += `REST ${note.duration}`;
        } else {
            let pitches = [this.getPitch(note)];
            let duration = note.duration;
            let type = "NOTE";
            let nextNote = allNotes[i + 1];

            if (note.isTied && !nextNote.isChord) {
                while (true) {
                    i++;
                    nextNote = allNotes[i];
                    if (nextNote.isTied) {
                        duration += nextNote.duration;
                    } else {
                        i--;
                        break;
                    }
                }
            }

            if (nextNote !== undefined && nextNote.isChord && !note.isTied) {
                type = "CHORD";
                while (i < allNotes.length - 1) {
                    i++;
                    nextNote = allNotes[i];
                    if (nextNote.isChord) {
                        pitches.push(this.getPitch(nextNote));
                    } else {
                        i--;
                        break;
                    }
                }
            }

            if (nextNote !== undefined && nextNote.isChord && note.isTied) {
                type = "CHORD";
                let chords = [];
                let lastNote = note;
                while (true) {
                    i++;
                    nextNote = allNotes[i];
                    if (nextNote === undefined) {
                        break;
                    }

                    if (!nextNote.isChord) {
                        chords.push(pitches);
                        pitches = [this.getPitch(nextNote)];
                    }

                    if (nextNote.isChord) {
                        pitches.push(this.getPitch(nextNote));
                    } else if (!nextNote.isTied || (nextNote.tiedType == "start" && lastNote.tiedType == "stop")) {
                        i--;
                        break;
                    }

                    if (nextNote.isTied && !nextNote.isChord) {
                        duration += nextNote.duration;
                    }
                    lastNote = nextNote;
                }
                pitches = chords[0];
            }

            if (note.isTremolo) {
                type = "TRILL";
                while (true) {
                    i++;
                    nextNote = allNotes[i];
                    if (nextNote === undefined) {
                        i--;
                        break;
                    }
                    if (nextNote.isTremolo) {
                        pitches.push(this.getPitch(nextNote));
                        duration += nextNote.duration;
                    } else {
                        i--;
                        break;
                    }
                    if (nextNote.tremoloType === "stop") {
                        break;
                    }
                }
            }

            if (pitches.length > 1) {
                score += `${type} (${pitches.join(" ")}) ${duration}`;
            } else {
                score += `${type} ${pitches[0]} ${duration}`;
            }
            if (note.isTied) {
                score += " // tied";
            }
        }
    }

    this.codeEditor.setValue(score);
    this.handleCodeChange();
}

export function parseScore(doc) {
    const part = doc.getElementsByTagName("score-partwise")[0];
    const measures = part.getElementsByTagName("measure");
    let bpm = 60;
    let beatUnit = "quarter";
    this.musicxmlScore = {};
    this.musicxmlScore.measures = {};
    let isTremolo = false;
    let isTied = false;
    let tremoloType = null;
    let tiedType = null;
    let credits = part.getElementsByTagName("credit");
    if (credits.elements !== 0) {
        for (let credit of credits) {
            let creditType = credit.getElementsByTagName("credit-type")[0];
            if (creditType) {
                let text = creditType.textContent;
                if (text == "title") {
                    let creditWords = credit.getElementsByTagName("credit-words");
                    if (creditWords.length > 0) {
                        this.musicxmlScore.pieceName = creditWords[0].textContent;
                    }
                } else if (text == "composer") {
                    let creditWords = credit.getElementsByTagName("credit-words");
                    if (creditWords.length > 0) {
                        this.musicxmlScore.pieceComposer = creditWords[0].textContent;
                    }
                }
            }
        }
    }

    let divisionsFactor = 1;
    for (let measure of measures) {
        let divisions = measure.getElementsByTagName("divisions");
        if (divisions.length > 0) {
            divisionsFactor = parseFloat(divisions[0].textContent);
        }
        let metronome = measure.getElementsByTagName("metronome")[0];
        if (metronome) {
            beatUnit = metronome.getElementsByTagName("beat-unit")[0].textContent;
            bpm = metronome.getElementsByTagName("per-minute")[0].textContent;
        }
        let measureNumber = measure.getAttribute("number");
        let notes = measure.getElementsByTagName("note");
        let measureNotes = [];
        for (let i = 0; i < notes.length; i++) {
            let note = notes[i];
            let chord = note.getElementsByTagName("chord").length;
            let pitch = note.getElementsByTagName("pitch")[0];
            let tremolo = note.getElementsByTagName("tremolo");
            let tied = note.getElementsByTagName("tied");
            if (tremolo.length > 0) {
                isTremolo = true;
                tremoloType = tremolo[0].getAttribute("type");
            } else {
                isTremolo = false;
                tremoloType = null;
            }
            if (tied.length > 0) {
                isTied = true;
                tiedType = tied[0].getAttribute("type");
            } else {
                isTied = false;
                tiedType = null;
            }
            let step, octave, alter;
            if (!pitch) {
                step = null;
                octave = null;
            } else {
                step = pitch.getElementsByTagName("step")[0].textContent;
                octave = pitch.getElementsByTagName("octave")[0].textContent;
                const alterElement = pitch.getElementsByTagName("alter")[0];
                if (alterElement) {
                    alter = parseInt(alterElement.textContent);
                } else {
                    alter = null;
                }
            }

            let duration = note.getElementsByTagName("duration");
            if (duration.length == 0) {
                duration = 0;
            } else {
                duration = note.getElementsByTagName("duration")[0].textContent;
            }

            let rest = note.getElementsByTagName("rest")[0];
            let noteObj = {
                bpm: bpm,
                step: step,
                octave: octave,
                alter: alter,
                duration: parseFloat(duration) / divisionsFactor,
                isRest: false,
                isTremolo: isTremolo,
                tremoloType: tremoloType,
                isTied: isTied,
                tiedType: tiedType,
                measureNumber: measureNumber,
                isChord: chord == 1,
                firstChordNote: false,
            };
            if (rest) {
                noteObj.isRest = true;
            }
            measureNotes.push(noteObj);
        }
        this.musicxmlScore.measures[measureNumber] = {};
        this.musicxmlScore.measures[measureNumber] = measureNotes;
    }
    this.generateOpenScofoScore();
    this.handleCodeChange();
}

export function uploadWav() {
    const fileInput = document.getElementById("audioInput");
    if (!fileInput) {
        console.error("File input not found");
        return;
    }
    fileInput.click();
    fileInput.onchange = (event) => {
        const file = event.target.files[0];
        if (!file) {
            console.error("No file selected");
            return;
        }
        console.log(file);
        k;
    };
}

export function uploadScore() {
    const fileInput = document.getElementById("scoreXmlInput");
    if (!fileInput) {
        console.error("File input not found");
        return;
    }
    fileInput.click();
    fileInput.onchange = (event) => {
        const file = event.target.files[0];
        if (!file) {
            console.error("No file selected");
            return;
        }

        if (file.name.endsWith(".mxl")) {
            const reader = new FileReader();
            reader.onload = (e) => {
                JSZip.loadAsync(e.target.result)
                    .then((zip) => {
                        const xmlFile = Object.keys(zip.files).find(
                            (fileName) => fileName.endsWith(".xml") && !fileName.includes("META-INF/"),
                        );
                        console.log(xmlFile);
                        if (xmlFile) {
                            zip.file(xmlFile)
                                .async("string")
                                .then((xmlString) => {
                                    const parser = new DOMParser();
                                    const doc = parser.parseFromString(xmlString, "application/xml");
                                    this.parseScore(doc);
                                })
                                .catch((error) => {
                                    alert("Error parsing XML:", error);
                                });
                        } else {
                            alert("No XML file found in the ZIP archive.");
                        }
                    })
                    .catch((error) => {
                        alert("Error extracting MXL file:", error);
                    });
            };
            reader.onerror = (error) => {
                alert("There was an error reading the file:", error);
            };
            reader.readAsArrayBuffer(file);
        } else if (file.name.endsWith(".xml") || file.name.endsWith(".musicxml")) {
            const reader = new FileReader();
            reader.onload = (e) => {
                const xmlString = e.target.result;
                const parser = new DOMParser();
                const doc = parser.parseFromString(xmlString, "application/xml");
                this.parseScore(doc);
            };
            reader.onerror = (error) => {
                alert("There was an error reading the file:", error);
            };
            reader.readAsText(file);
        } else {
            alert("Unsupported file type");
        }
    };
}

export function loadTxtScore() {
    const fileInput = document.getElementById("scoreTxtInput");
    if (!fileInput) {
        console.error("File input not found");
        return;
    }

    fileInput.click();
    fileInput.onchange = (event) => {
        const file = event.target.files[0];
        if (!file) {
            console.error("No file selected");
            return;
        }
        const reader = new FileReader();
        reader.onload = (e) => {
            const fileContent = e.target.result;
            this.codeEditor.setValue(fileContent);

            this.handleCodeChange();
        };
        reader.onerror = (e) => {
            console.error("Error reading file:", e);
        };
        reader.readAsText(file);
    };
}